name: Coverage

on:
  push:
    branches: ['main']
    paths-ignore: ['**.md', 'docs/**']
  pull_request:
    paths-ignore: ['**.md', 'docs/**']
  workflow_dispatch:

concurrency:
  group: 'coverage-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Generate Report
      run: |
        pip install wheel
        pip install pytest-cov
        pip install dask[array,dataframe,distributed,diagnostics]
        pip install -q --no-cache-dir -e .[complete,test]
        pytest --cov=dask_awkward --cov-report=xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
